### ISSUE TITLE
Hardware acceleration on RK3568B2

### ISSUE THREAD

**Issue by danergo** [hbiyik/FFmpeg#1]
I wish to have an ffmpeg which can transcode h264 or hevc source to h264 with lower fps/resolution/bitrate by hardware acceleration on RK3568B2. Can any of your repository be a good choice?

Note: I tried with https://github.com/jjm2473/ffmpeg-rk, but it segfaults constantly, and repository owner is not responding to my questions.

I have a RK3568 CPU (nanopi r5c), with this os: rk3568-eflasher-debian-bullseye-core-5.10-arm64-YYYYMMDD.img.gz

How shall I (from which repos) build or (from which packages) install the dependencies?

What are the dependencies? Librga and mpp?

What is the recommended configure command?

Thank you very much.

**Comment by danergo** [comment]
Hi, @hbiyik: can you please help me with this?
Thank you.

**Comment by hbiyik** [comment]
I think i have read incorrectly your previous message. Those repositoties have only changes on how to output the decoded data. None of them have encoder support. To transcode you need encoder, so this repo can not help you in that.

**Comment by danergo** [comment]
Ah, okay, thank you! :)
