### ISSUE TITLE
How to use encoder on RK3399 and use it in Jellyfin

### ISSUE THREAD

**Issue by zhu327** [hbiyik/FFmpeg#10]
Is it possible to use an RK3399 SBC for hardware decoding in Jellyfin?

**Comment by hbiyik** [comment]
Should work, i dont have an 3399 to test it though. Try encoder branch, i would say.

**Comment by zhu327** [comment]
how to compile encoder branch?

**Comment by hbiyik** [comment]
Ideally --enable-rkmpp is the configure flag you need as extra addition to normal ffmpeg compiliation.

Adfitionally when rkmpp is enabled, you will need [libyuv](https://chromium.googlesource.com/libyuv/libyuv/)  as an extra dependency along with normal ffmpeg dependencies.

In case any doubt you can refer to below arch build script
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ffmpeg-mpp

**Comment by hbiyik** [comment]
added on the wiki https://github.com/hbiyik/FFmpeg/wiki#compilation
