### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by primoitt83** [hbiyik/FFmpeg#2]
Hi!! Can i build this project on armhf linux?

My Soc is RK3229.. thx!!

**Comment by hbiyik** [comment]
hello, i do not see why not, but i have to admit i have never tried. It should work though, please report in case any issues.

**Comment by primoitt83** [comment]
Ok! Thx for reply!

Is it possible to clone this tree?

https://github.com/hbiyik/FFmpeg/tree/libyuv

My git skills are not good..

**Comment by hbiyik** [comment]
No, this branch is already merged in mpp-rga-ffmpeg-6. So you can use this one.
