### ISSUE TITLE
build FFmpeg with rkmmp for VLC

### ISSUE THREAD

**Issue by franalta** [hbiyik/FFmpeg#21]
Good morning, I hope that is the right place to make this question (if it isn't, please help me on other channel or tell me where post). My goal is use vlc media player on my rockchip device RK3228 (I don't know if it's a RK3228A or a RK3228B) to play blu-ray (both encrypted that decrypted) using hardware acceleration. So after made some research I have found this article https://www.omgubuntu.co.uk/2022/08/watch-bluray-discs-in-vlc-on-ubuntu-with-makemkv that have redirect here https://forum.makemkv.com/forum/viewtopic.php?f=3&t=224 and here https://forum.makemkv.com/forum/viewtopic.php?f=3&t=7009 . After follow their instruction and tried to play a blu-ray image not decrypted (https://durian.blender.org/download/ ) vlc seems not working but it was working very slow (have just showed a frame with some squares) because it don't was using hardware decoding. So I have made a new search founding this post https://forum.odroid.com/viewtopic.php?p=349030&sid=a3a43262cde743666ca2581a6b1db4a7#p349030 and downloading rkmpp framework https://github.com/rockchip-linux/mpp .
The first question is: can I apply the same steps listed to your repository (obviously branch mpp-rga-ffmpeg-6)?

Go on in my search I have found also this post https://forum.pine64.org/showthread.php?tid=6373&pid=39854#pid39854 where is written "video player must request "h264_rkmpp", "hevc_rkmpp", "vp8_rkmpp" or "vp9_rkmpp" decoder from ffmpeg" . So the second question is: can I edit renaming (and in what file) h264_rkmpp constant ecc inside ffmpeg source so VLC use h264 hw accelerated decoding ?

I'm newbie on linux, but hope that somebody it's interested to use vlc as blu-ray player such me and/or motivated to help me .

Best regards

**Comment by franalta** [comment]
nobody?

**Comment by hbiyik** [comment]
you just need to build ffmpeg with shared library options. VLC will auto load the libraries

**Comment by franalta** [comment]
thank You for the answer, but I should also add makemkv to play encrypted blu-ray... if You have a rockchipdevice that use media process platform and that boot from sd, can You make a video tutorial starting from a clean installation of armbian (or write steps accomplished with image) to use vlc with makemkv and rockchip fork of ffmpeg ? Sadly I don't know how to move between make and cmake utility

**Comment by hbiyik** [comment]
Contact the distro for such requests
