### ISSUE TITLE
brakes build

### ISSUE THREAD

**Issue by great9** [hbiyik/FFmpeg#24]
https://github.com/hbiyik/FFmpeg/blob/e243e8d0010dfdaab0a9e3f9bb94dba7a2c51c69/libavcodec/rkmpp.c#L34

**Comment by hbiyik** [comment]
?

**Comment by ielenik** [comment]
Just a guess - in case of old mpp RK_FORMAT_BGR_565 will be unresolved

**Comment by MarcA711** [comment]
I had the same issue. The reason was an old version of `librga`. Can be fixed by installing `librga2` and `librga-dev` from here (use the newest version for your distro): http://ppa.linuxfactory.or.kr/pool/rockchip/libr/librga/

**Comment by hbiyik** [comment]
always use the latest rga-multi, semi-official branch is here:
https://github.com/JeffyCN/mirrors/tree/linux-rga-multi

i will also remove BGR565 since it is not used at all.
