### ISSUE TITLE
Static binary

### ISSUE THREAD

**Issue by MrPlatnum** [hbiyik/FFmpeg#26]
Is there a way to compile this source code into a static binary?
I need a static one because i want to use it with frigate, which requieres a static binary.

**Comment by hbiyik** [comment]
yes should be possible, check ffmpeg documentation

**Comment by MrPlatnum** [comment]
Thank you for your response.
I got a bunch of issues with the rkmpp lib itself apart from that it works fine.
Did you ever manage to compile the mpp lib staticly and also link it in ffmpeg?
I unfortunately always get a bunch of undefined references and pkg-config can't find it.

**Comment by hbiyik** [comment]
I never tried static linking mpp to libavcodec
