### ISSUE TITLE
increase performance?

### ISSUE THREAD

**Issue by AIhasArrived** [hbiyik/FFmpeg#31]
Was anyone able to have faster porcessing with FFMPEG? 
I have a bunch of GPU but it is using very little, and it is being VERY SLOW at making a video out of frames I collected.
Any insignt would be appreciated.
thanks

**Comment by hbiyik** [comment]
i am closing this issue, this repo has nothing to do gpus i think you are misinformed
feel free to reopen if you have a question related to rockchip vpu hardware and decoder. Please check wiki for more

**Comment by AIhasArrived** [comment]
This is about FFMpeg, the tool that is used to convert mp4 to mp3 or connect multiple mp3 into one single one, no? @hbiyik
