### ISSUE TITLE
how to check os hardware is working?

### ISSUE THREAD

**Issue by wnpllrzodiac** [hbiyik/FFmpeg#32]
I built ffmpeg out but cannot decode correctly. maybe hardware not working well?

chipset: rk3566
os: Armbian 23.11.0-trunk Lunar

[h264_rkmpp @ 0x55969d1fe0] Failed to initialize MPP context (code = -1).
[h264_rkmpp @ 0x55969d1fe0] Failed to initialize RKMPP decoder.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_rkmpp) -> h264 (h264_rkmpp))
Error while opening decoder for input stream #0:0 : Unknown error occurred

**Comment by hbiyik** [comment]
mpp requires vendor(rockchip) kernel.
if you are on vendor kernel, you can check why mpp is complaining from `journalctl -f`

**Comment by wnpllrzodiac** [comment]
yeah, I found that kernel without mpp support

```
Nov 18 13:07:31 armbian mpp[5186]: mpp_info: mpp version: unknown mpp version for missing VCS info
Nov 18 13:07:31 armbian mpp[5186]: vcodec_service: open vcodec_service (null) failed
Nov 18 13:07:31 armbian mpp[5186]: hal_h264e_vepu541: hal_h264e_vepu541_init mpp_dev_init failed. ret: -1
Nov 18 13:07:31 armbian mpp[5186]: mpp_enc_hal: mpp_enc_hal_init hal hal_h264e init failed ret -1
Nov 18 13:07:31 armbian mpp[5186]: mpp_enc_hal: mpp_enc_hal_init could not found coding type 7
Nov 18 13:07:31 armbian mpp[5186]: mpp_enc: mpp_enc_init_v2 could not init enc hal
Nov 18 13:07:31 armbian mpp[5186]: mpp: error found on mpp initialization
```

**Comment by hbiyik** [comment]
Closing then
