### ISSUE TITLE
Hi! I got some situation when i run configure script

### ISSUE THREAD

**Issue by EZreal-zhangxing** [hbiyik/FFmpeg#4]
Hello thanks for your work

my system is ubuntu 20.04 with rockchip rk3588
and the main purpose is that decode or encode video with ffmpeg use hardwave

i clone your project and the branch is mpp-rga-ffmpeg-6

after that i run configure with parameters are list below
` ./configure --prefix=/usr/local/ --enable-shared --enable-version3 --enable-rkmpp --enable-libx264 --enable-gpl --enable-libdrm --enable-opencl --enable-nonfree`

and the output log is that
![1685517524400](https://github.com/hbiyik/FFmpeg/assets/8359625/b44c8d13-f95f-42fe-89bb-0e4e1fa3cb7a)

it's seems that code into deathloop and can not run out

can u please help me deal with that

**Comment by EZreal-zhangxing** [comment]
but it works well on windows  :/)

**Comment by hbiyik** [comment]
no idea, it runs ok on my machine, could be an issue with ffmpeg configure script. Does it change when you remove some flags from the configure command u issue?
