### ISSUE TITLE
decoder error 

### ISSUE THREAD

**Issue by ywangwxd** [hbiyik/FFmpeg#41]
I followed the instructions, 
1, compiled and installed mpp from git
2, compiled and installed libyuv from git
3, compiled and installed ffmpeg
but when I try to transcode a video, it showed error message :

``
[h264_rkmpp_decoder @ 0x55d029d760] Picture format is nv12.
[h264_rkmpp_decoder @ 0x55d029d760] Failed to initialize MPP context (code = -1).
[h264_rkmpp_decoder @ 0x55d029d760] Failed to initialize RKMPP Codec.
``

I tried mpp_info_test binary compiled from MPP source, it shows nothing. What is the problem?

**Comment by great9** [comment]
What kernel and linux distribution are you using?
`uname -a`

**Comment by ywangwxd** [comment]
5.10.110 #39 SMP Tue Nov 8 11:08:57 CST 2022 aarch64 GNU/Linux

I am using ubuntu, I did the compliation on the aarch64 system directly, not cross-compiling.

**Comment by hbiyik** [comment]
could ypu try decoding with sudo, if it works you need to enable access to mppservice, rga, heaps to the logged in user, you can check  udev rules below.

https://github.com/7Ji-PKGBUILDs/mpp-git/blob/master/60-mpp.rules
https://github.com/7Ji-PKGBUILDs/mpp-git/blob/master/install

**Comment by ywangwxd** [comment]
Yes, it is working if I change the input to a rtsp stream or a h265 file, but not on a mp4 file.
